// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisTicket.Infrastructure.Persistence.Context;

#nullable disable

namespace SisTicket.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112143256_AgregarSoftDelete")]
    partial class AgregarSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CargadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CargadoPorId");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_Adjuntos_FechaCreacion");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("IX_Adjuntos_SolicitudId");

                    b.ToTable("Adjuntos", (string)null);
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Areas_Nombre");

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Área encargada de soporte técnico, desarrollo y mantenimiento de sistemas",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Tecnología de la Información"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Gestión de personal, nómina y desarrollo organizacional",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Control presupuestario, contabilidad y tesorería",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Finanzas"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Gestión de procesos operativos y logística",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Operaciones"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Servicios generales y gestión administrativa",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administración"
                        });
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValoresAntiguos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("TipoAccion");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Entidad", "EntidadId");

                    b.ToTable("AuditoriaLogs", (string)null);
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_Comentarios_FechaCreacion");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("IX_Comentarios_SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios", (string)null);
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nivel")
                        .HasDatabaseName("IX_Prioridades_Nivel");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Prioridades_Nombre");

                    b.ToTable("Prioridades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Solicitud sin urgencia, puede resolverse en tiempo extendido",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nivel = 1,
                            Nombre = "Baja"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Solicitud con prioridad normal, debe atenderse en tiempo razonable",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nivel = 2,
                            Nombre = "Media"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Solicitud urgente, requiere atención prioritaria",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nivel = 3,
                            Nombre = "Alta"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Solicitud crítica, requiere atención inmediata",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nivel = 4,
                            Nombre = "Crítica"
                        });
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GestorAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSolicitud")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoSolicitudId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Solicitudes_Estado");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_Solicitudes_FechaCreacion");

                    b.HasIndex("GestorAsignadoId");

                    b.HasIndex("NumeroSolicitud")
                        .IsUnique()
                        .HasDatabaseName("IX_Solicitudes_NumeroSolicitud");

                    b.HasIndex("PrioridadId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("TipoSolicitudId");

                    b.ToTable("Solicitudes", (string)null);
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.TipoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("IX_TiposSolicitud_AreaId");

                    b.HasIndex("Nombre", "AreaId")
                        .IsUnique()
                        .HasDatabaseName("IX_TiposSolicitud_Nombre_AreaId");

                    b.ToTable("TiposSolicitud", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            AreaId = 1,
                            Descripcion = "Solicitudes relacionadas con problemas técnicos de hardware o software",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Soporte Técnico"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            AreaId = 1,
                            Descripcion = "Solicitudes de mantenimiento preventivo o correctivo de equipos",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Mantenimiento"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            AreaId = 1,
                            Descripcion = "Solicitudes de nuevas funcionalidades o servicios tecnológicos",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Nuevo Requerimiento"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            AreaId = 1,
                            Descripcion = "Reporte de problemas o errores en sistemas",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Incidencia"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            AreaId = 1,
                            Descripcion = "Solicitudes relacionadas con accesos a sistemas o permisos",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Acceso y Permisos"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            AreaId = 2,
                            Descripcion = "Solicitudes de información o asesoría de recursos humanos",
                            Eliminado = false,
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Consulta"
                        });
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_NombreUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Motos",
                            AreaId = 1,
                            Eliminado = false,
                            Email = "cesar@gmail.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Cesar",
                            NombreUsuario = "cesar",
                            PasswordHash = "AQAAAAIAAYagAAAAECesarPasswordHashNeedsToBeReplacedWithRealHashInProduction",
                            Rol = 4
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellido = "TI",
                            AreaId = 1,
                            Eliminado = false,
                            Email = "admin@gmail.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador",
                            NombreUsuario = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEPasswordHashNeedsToBeReplacedWithRealHashInProduction",
                            Rol = 3
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellido = "Técnico",
                            AreaId = 1,
                            Eliminado = false,
                            Email = "gestor@gmail.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Gestor",
                            NombreUsuario = "gestor",
                            PasswordHash = "AQAAAAIAAYagAAAAEPasswordHashNeedsToBeReplacedWithRealHashInProduction",
                            Rol = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellido = "Demostración",
                            AreaId = 2,
                            Eliminado = false,
                            Email = "usuario@gmail.com",
                            FechaCreacion = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Solicitante",
                            NombreUsuario = "usuario",
                            PasswordHash = "AQAAAAIAAYagAAAAEPasswordHashNeedsToBeReplacedWithRealHashInProduction",
                            Rol = 1
                        });
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Adjunto", b =>
                {
                    b.HasOne("SisTicket.Core.Domain.Entities.Usuario", "CargadoPor")
                        .WithMany()
                        .HasForeignKey("CargadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisTicket.Core.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Adjuntos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargadoPor");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("SisTicket.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Comentario", b =>
                {
                    b.HasOne("SisTicket.Core.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Comentarios")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisTicket.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("SisTicket.Core.Domain.Entities.Area", "Area")
                        .WithMany("Solicitudes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisTicket.Core.Domain.Entities.Usuario", "GestorAsignado")
                        .WithMany("SolicitudesAsignadas")
                        .HasForeignKey("GestorAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SisTicket.Core.Domain.Entities.Prioridad", "Prioridad")
                        .WithMany("Solicitudes")
                        .HasForeignKey("PrioridadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisTicket.Core.Domain.Entities.Usuario", "Solicitante")
                        .WithMany("SolicitudesCreadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisTicket.Core.Domain.Entities.TipoSolicitud", "TipoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("GestorAsignado");

                    b.Navigation("Prioridad");

                    b.Navigation("Solicitante");

                    b.Navigation("TipoSolicitud");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.TipoSolicitud", b =>
                {
                    b.HasOne("SisTicket.Core.Domain.Entities.Area", "Area")
                        .WithMany("TiposSolicitud")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SisTicket.Core.Domain.Entities.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Area", b =>
                {
                    b.Navigation("Solicitudes");

                    b.Navigation("TiposSolicitud");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Prioridad", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.TipoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SisTicket.Core.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("SolicitudesAsignadas");

                    b.Navigation("SolicitudesCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
